Repository ubsuny/CP1-24-HW3, pull requests merged in 2024-10, with the labels that each got.

#17 Moved the configuration file into a new folder and renamed it to properly set up the codespace.
  .devcontainer/python/devcontainer.json
Labels: bug, python, codespace, github

#19 Created a Pull Request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#37 Docs and .gitignore file
  .gitignore
  documentation/testDrivenDevelopment.md
Labels: documentation, github

#23 Reactance
  reactance/reactance.md
  reactance/reactance.py
  reactance/unit_tests.py
Labels: enhancement, python

#28 Resistance in a wire functional program.
  ResistanceInAWire/resistance_in_a_wire_algorithm.py
  ResistanceInAWire/test_resistance_in_a_wire.py
Labels: python

#30 Circuit parallel
  Parallel_circuit.md
  circuit_parallel.py
Labels: documentation, python

#32 Coulomb's law
  CoulombsLaw/coulomb.py
  CoulombsLaw/coulombmain.py
  CoulombsLaw/coulumbtest.py
Labels: python

#38 Implemented PoyntingVector module
  PoyntingVectorModule/PoyntingVectorTheory.md
  PoyntingVectorModule/poynting_vector.py
  PoyntingVectorModule/test_poynting_vector.py
  __pycache__/PoyntingVector.cpython-312.pyc
  __pycache__/TestPoyntingVector.cpython-312-pytest-8.3.3.pyc
Labels: documentation, enhancement

#46 Added three modules to calculate the surface charge density of a sphere of radius (R) held at constant potential (V) and test for it.
  SphereSurfaceChargeDensity/math_ops_module.py
  SphereSurfaceChargeDensity/physics_module.py
  SphereSurfaceChargeDensity/unit_testing_module.py
Labels: enhancement, physics

#55 Added Lorentz force module and unit tests
  TaskAssignmentsList_HW3.ipynb
  lorentz_force/lorentz_force.py
  lorentz_force/lorentz_unit_tests.py
Labels: enhancement

#63 Solving for capacitance of spherical capacitor
  spherical_capacitance/spherical_capacitance.md
  spherical_capacitance/spherical_capacitor.py
  spherical_capacitance/unit_test.py
Labels: enhancement, physics, python
